#!/usr/bin/env bash
# Install the standard Compose stack without Go/Node on the host.
set -Eeuo pipefail
ROOT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
cd "$ROOT_DIR"
source "$ROOT_DIR/deploy/scripts-common.sh"
RESUME=0
case ${1:-} in
  --help|-h) printf '用法：./install.sh [--resume]\n首次安装生成 .env；失败后用 --resume 沿用凭据重试。\n'; exit 0 ;;
  --resume) [[ $# == 1 ]] || fail '用法：./install.sh [--resume]'; RESUME=1 ;;
  '') [[ $# == 0 ]] || fail '用法：./install.sh [--resume]' ;;
  *) fail '用法：./install.sh [--resume]' ;;
esac
require_tools docker openssl python3 mktemp
[[ -f compose.yaml ]] || fail '找不到 compose.yaml'
PROJECT=deepseek-audit
acquire_lock
temp_env=''
cleanup() {
  [[ -z $temp_env ]] || rm -f -- "$temp_env"
  rmdir "$LOCK_DIR"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
if (( RESUME )); then
  [[ -f .env && ! -L .env ]] || fail '没有普通 .env 文件，首次安装请直接运行 ./install.sh'
  grep -Fxq '# Generated by deepseek-moderation-api install.sh' .env || fail '现有 .env 不是本脚本生成的；已有部署请运行 ./update.sh 或按 UPGRADE.zh.md 手动更新'
  grep -Fxq "COMPOSE_PROJECT_NAME=$PROJECT" .env || fail 'Compose 项目名已改变，不能继续安装'
  chmod 600 .env
else
  [[ ! -e .env && ! -L .env ]] || fail '已有 .env；更新请用 ./update.sh，首次安装失败可用 ./install.sh --resume'
fi
python3 "$ROOT_DIR/deploy/compose_guard.py" install "$ROOT_DIR" "$PROJECT" "$RESUME"
if (( ! RESUME )); then
  master_key=$(openssl rand -base64 32 | tr -d '\r\n')
  admin_password=$(openssl rand -hex 24)
  postgres_password=$(openssl rand -hex 24)
  [[ -n $master_key && -n $admin_password && -n $postgres_password ]] || fail '随机凭据生成失败'
  temp_env=$(mktemp "$ROOT_DIR/.env.tmp.XXXXXX")
  printf '# Generated by deepseek-moderation-api install.sh\nCOMPOSE_PROJECT_NAME=%s\nMASTER_KEY=%s\nADMIN_USER=admin\nADMIN_PASSWORD=%s\nPOSTGRES_PASSWORD=%s\nPUBLIC_URL=http://localhost:8090\n' \
    "$PROJECT" "$master_key" "$admin_password" "$postgres_password" > "$temp_env"
  chmod 600 "$temp_env"
  # A hard link publishes the complete file and cannot overwrite an existing .env.
  ln "$temp_env" .env || fail '无法创建 .env，已有文件不会被覆盖'
  rm -f -- "$temp_env"
  temp_env=''
fi
compose config --no-env-resolution --format json | python3 "$ROOT_DIR/deploy/compose_guard.py" resume "$ROOT_DIR" "$PROJECT"
compose up -d --build || fail '构建或启动失败；凭据保存在 .env，排查后运行 ./install.sh --resume'
container=$(compose ps -q app)
[[ -n $container ]] && wait_healthy "$container" || fail '应用未通过健康检查；查看 docker compose logs，排查后运行 ./install.sh --resume'
printf '\n安装完成，应用与数据库已通过健康检查。\n访问地址：http://localhost:8090（远程服务器请使用 SSH 隧道或 HTTPS 反向代理）\n账号：admin；初始密码在 .env 的 ADMIN_PASSWORD 中（不输出到日志）。\n后续更新：./update.sh\n'
