<script setup lang="ts">
import {
  Activity,
  Archive,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  CalendarDays,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  Clock3,
  Coins,
  Copy,
  Cpu,
  Database,
  FileText,
  FlaskConical,
  Gauge,
  KeyRound,
  ImagePlus,
  Upload,
  LayoutDashboard,
  Link,
  LockKeyhole,
  LogOut,
  Menu,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Save,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Trash2,
  Wallet,
  X,
  Zap,
} from "@lucide/vue";
const icons = {
  activity: Activity,
  archive: Archive,
  download: ArrowDownToLine,
  back: ArrowLeft,
  next: ArrowRight,
  bars: BarChart3,
  calendar: CalendarDays,
  chart: ChartNoAxesCombined,
  check: Check,
  down: ChevronDown,
  chevron: ChevronRight,
  help: CircleHelp,
  clock: Clock3,
  coins: Coins,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  file: FileText,
  flask: FlaskConical,
  gauge: Gauge,
  key: KeyRound,
  image: ImagePlus,
  upload: Upload,
  overview: LayoutDashboard,
  link: Link,
  lock: LockKeyhole,
  logout: LogOut,
  menu: Menu,
  edit: Pencil,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  save: Save,
  settings: Settings2,
  shield: ShieldCheck,
  filters: SlidersHorizontal,
  trash: Trash2,
  wallet: Wallet,
  close: X,
  zap: Zap,
};
defineProps<{ name: keyof typeof icons; size?: number }>();
</script>

<template>
  <component
    :is="icons[name]"
    :size="size || 18"
    :stroke-width="1.7"
    aria-hidden="true"
    class="app-icon"
  />
</template>
